### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by xcony** [formslider/formslider.github.io#1]
I have a problem to make the script actually initialize or start working when I follow the instructions. Maybe I miss something? 

I did:
`bower install jquery.formslider --save` // which generated formslider directory
created index.html (see below) 

index.html:
```
<html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="/xcn/formslider/node_modules/jquery.formslider/dist/jquery.formslider.dependencies.min.js"></script>
<script src="/xcn/formslider/node_modules/jquery.formslider/dist/jquery.formslider.min.js"></script>

<link rel="stylesheet" href="/xcn/formslider/node_modules/jquery.formslider/dist/formslider.min.css">

<body>

![screen](https://user-images.githubusercontent.com/20482851/36096408-922dd912-0ff6-11e8-98cb-d4af31ec86e8.png)
![screen](https://user-images.githubusercontent.com/20482851/36096436-b126498a-0ff6-11e8-967f-08ab87057f5c.png)
<form>
  <div class="formslider-wrapper">
    <div class="formslider">

      <div class="slide" data-role="question">
        <div class="headline">Are you a man or a woman?</div>
        <label class="answer">
          <div class="text">man</div>
        </label>
        <label class="answer">
          <div class="text">women</div>
        </label>
      </div>

      <div class="slide" data-role="zipcode">
        <div class="headline">Where do you live?</div>
        <label for="contact_zipcode">zip code</label>
        <input type="number" required="required">
        <a class="next-button" href="#">continue</a>
      </div>

      <div class="slide" data-role="loader">
        <div class="headline">Please wait!</div>
        <div class="sub-headline">It does not take long.</div>
      </div>

      <div class="slide" data-role="confirmation">
        <div class="headline">Thank you for your interest</div>
        <div class="sub-headline">You hear from me as soon as possible.</div>
      </div>

    </div>
  </div>
</form>  

<div class="progressbar-wrapper">
  <div class="progress-text"></div>
  <div class="progress-bar">
    <div class="progress"></div>
  </div>
</div>

<script>
(function($){

  $('.formslider-wrapper').formslider();

})(jQuery);
</script>


</body>
</html>

```

this is the test-result:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'browse' ]
2 info using npm@3.5.2
3 info using node@v6.11.4
4 verbose stack Error: ENOENT: no such file or directory, open '/var/www/html/formslider/package.json'
4 verbose stack     at Error (native)
5 verbose cwd /var/www/html/formslider
6 error Linux 4.13.0-19-generic
7 error argv "/usr/bin/node" "/usr/bin/npm" "run" "browse"
8 error node v6.11.4
9 error npm  v3.5.2
10 error path /var/www/html/formslider/package.json
11 error code ENOENT
12 error errno -2
13 error syscall open
14 error enoent ENOENT: no such file or directory, open '/var/www/html/formslider/package.json'
15 error enoent ENOENT: no such file or directory, open '/var/www/html/formslider/package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -2, true ]

**Comment by tomhanoldt** [comment]
"npm run browse" or the npm packages in generally are meant for development. You just have to open your index.html file in your browser. 

You say you did "bower install jquery-formslider --save" but you include node_modules in your html file? The simplest way for integration is to use only bower for dependency management (or bower via yarn).

**Comment by xcony** [comment]
Thanks for your reply!

When I open index.html it shows this screen:
https://user-images.githubusercontent.com/20482851/36096408-922dd912-0ff6-11e8-98cb-d4af31ec86e8.png

I did:
bower install jquery.formslider --save

I modified my index.html to this:
```
<html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="/xcn/formslider/bower_components/jquery.formslider/dist/jquery.formslider.dependencies.min.js"></script>
<script src="/xcn/formslider/bower_components/jquery.formslider/dist/jquery.formslider.min.js"></script>

<link rel="stylesheet" href="/xcn/formslider/bower_components/jquery.formslider/dist/formslider.min.css">

<body>
<form>
  <div class="formslider-wrapper">
    <div class="formslider">

      <div class="slide" data-role="question">
        <div class="headline">Are you a man or a woman?</div>
        <label class="answer">
          <div class="text">man</div>
        </label>
        <label class="answer">
          <div class="text">women</div>
        </label>
      </div>

      <div class="slide" data-role="zipcode">
        <div class="headline">Where do you live?</div>
        <label for="contact_zipcode">zip code</label>
        <input type="number" required="required">
        <a class="next-button" href="#">continue</a>
      </div>

      <div class="slide" data-role="loader">
        <div class="headline">Please wait!</div>
        <div class="sub-headline">It does not take long.</div>
      </div>

      <div class="slide" data-role="confirmation">
        <div class="headline">Thank you for your interest</div>
        <div class="sub-headline">You hear from me as soon as possible.</div>
      </div>

    </div>
  </div>
</form>  

<div class="progressbar-wrapper">
  <div class="progress-text"></div>
  <div class="progress-bar">
    <div class="progress"></div>
  </div>
</div>

<script>
(function($){
  $('.formslider-wrapper').formslider();
})(jQuery);
</script>
</body>
</html>

```
```
# ls bower_components/ -la
drwxr-xr-x  8 root     root     4096 Feb 12 13:36 bootstrap
drwxr-xr-x  5 root     root     4096 Feb 13 12:35 flexslider
drwxr-xr-x  5 root     root     4096 Feb 12 13:36 jquery
drwxr-xr-x  4 root     root     4096 Feb 13 12:35 jquery.debug
drwxr-xr-x  6 root     root     4096 Feb 13 12:35 jquery.formslider
drwxr-xr-x  5 root     root     4096 Feb 13 12:35 jquery-validation
drwxr-xr-x  3 root     root     4096 Feb 13 12:35 js-cookie
drwxr-xr-x  2 root     root     4096 Feb 13 12:35 js-url
```
Still not working. What am I missing here? Thanks for help!

**Comment by tomhanoldt** [comment]
Hey you are right, after the v1.1 release in the last days I didnt update the default configuration. This is now doen with version 1.1.2. I also created an minimalistic demo implementation: https://github.com/formslider/jquery.formslider.demo <https://github.com/formslider/jquery.formslider.demo>

Hope this helps =)


Tom Hanoldt
--------------------------
Software Engineer & Founder
Creative-Workflow
Gaudystraße 17A
10437 Berlin

Tel: 0176 49564869
E-Mail: monotom@gmail.com <mailto:monotom@gmail.com>
Web: http://www.creative-workflow.berlin <http://www.creative-workflow.berlin/>

http://www.tomhanoldt.info <http://www.tomhanoldt.info/>
http://www.xing.com/profile/Tom_Hanoldt <http://www.xing.com/profile/Tom_Hanoldt>
https://de.linkedin.com/pub/tom-hanoldt <https://de.linkedin.com/pub/tom-hanoldt/b0/a44/925>
